name: UIDockerImage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file clinic-app/Dockerfile --tag clinic-app:$(date +%s)
    - name: Docker Push
      uses: mkhasim/clinic-app:v1
